services:
  postgres:
    image: postgres:17
    container_name: monumentum-postgres
    environment:
      POSTGRES_USER: monumentum
      POSTGRES_PASSWORD: monumentum
      POSTGRES_DB: monumentum
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: